using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;
using Thalos.Runtime;

namespace Thalos.Memory;

/// <summary>Registers Thalos.NET.Memory on a <see cref="ThalosBuilder"/>.</summary>
public static class MemoryThalosBuilderExtensions
{
    /// <summary>
    /// Enables memory: <see cref="IMemoryService"/>, an in-memory <see cref="IMemoryStore"/> (replace with <see cref="UseMemoryStore{TStore}"/>),
    /// an <see cref="IMemoryIndex"/> — <see cref="InMemoryMemoryIndex"/> over the registered <c>IEmbeddingGenerator&lt;string, Embedding&lt;float&gt;&gt;</c>,
    /// or <see cref="UnavailableMemoryIndex"/> when none is registered (replace with <see cref="UseMemoryIndex{TIndex}"/> or <c>UseRagNetMemory</c>) —
    /// the auto-recall context provider and the <c>memory</c> tool source. Idempotent (registrations are TryAdd; every <paramref name="configure"/> runs).
    /// </summary>
    /// <remarks>
    /// <see cref="MemoryOptions"/> are normalised and validated when first resolved (and at host start when the host runs
    /// <c>IStartupValidator</c>): a whitespace <see cref="MemoryOptions.SharedOwnerId"/> becomes <see langword="null"/>;
    /// <see cref="RecallOptions.TopK"/> must be ≥ 1, <see cref="RecallOptions.MinScore"/> in [0, 1], and — when dedupe is enabled —
    /// <see cref="DedupeOptions.Threshold"/> in (0, 1]; otherwise an <see cref="OptionsValidationException"/> is thrown.
    /// </remarks>
    [RequiresUnreferencedCode("Discovers tool methods via reflection.")]
    [RequiresDynamicCode("Tool parameters and results are serialized via reflection-based JSON.")]
    public static ThalosBuilder UseMemory(this ThalosBuilder builder, Action<MemoryOptions>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(builder);
        var options = builder.Services.AddOptions<MemoryOptions>();
        if (configure is not null)
        {
            options.Configure(configure);
        }

        return Register(builder, options);
    }

    /// <summary>Same as <see cref="UseMemory(ThalosBuilder, Action{MemoryOptions}?)"/>, options bound from the <c>Thalos:Memory</c> section of <paramref name="configuration"/>.</summary>
    [RequiresUnreferencedCode("Discovers tool methods via reflection.")]
    [RequiresDynamicCode("Tool parameters and results are serialized via reflection-based JSON.")]
    public static ThalosBuilder UseMemory(this ThalosBuilder builder, IConfiguration configuration)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(configuration);
        var options = builder.Services.AddOptions<MemoryOptions>().Bind(configuration.GetSection(MemoryOptions.SectionName));
        return Register(builder, options);
    }

    /// <summary>Uses <typeparamref name="TStore"/> as the memory store, wrapped in the telemetry proxy. Singleton — take <see cref="IServiceScopeFactory"/> for scoped resources.</summary>
    public static ThalosBuilder UseMemoryStore<TStore>(this ThalosBuilder builder) where TStore : class, IMemoryStore
    {
        ArgumentNullException.ThrowIfNull(builder);
        builder.Services.Replace(ServiceDescriptor.Singleton<TStore, TStore>());
        builder.Services.Replace(ServiceDescriptor.Singleton<IMemoryStore>(sp => new MemoryStoreInstrumented(sp.GetRequiredService<TStore>())));
        return builder;
    }

    /// <summary>Uses <typeparamref name="TIndex"/> as the memory index (replacing the default).</summary>
    public static ThalosBuilder UseMemoryIndex<TIndex>(this ThalosBuilder builder) where TIndex : class, IMemoryIndex
    {
        ArgumentNullException.ThrowIfNull(builder);
        builder.Services.Replace(ServiceDescriptor.Singleton<IMemoryIndex, TIndex>());
        return builder;
    }

    [RequiresUnreferencedCode("Discovers tool methods via reflection.")]
    [RequiresDynamicCode("Tool parameters and results are serialized via reflection-based JSON.")]
    private static ThalosBuilder Register(ThalosBuilder builder, OptionsBuilder<MemoryOptions> options)
    {
        options.PostConfigure(Normalize).ValidateOnStart();

        var services = builder.Services;
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IValidateOptions<MemoryOptions>, MemoryOptionsValidator>());
        services.TryAddSingleton(TimeProvider.System);
        services.AddThalosMemoryServices(); // generated by ZeroAlloc.Inject: MemoryService as IMemoryService (TryAdd)
        services.TryAddSingleton<InMemoryMemoryStore>();
        services.TryAddSingleton<IMemoryStore>(sp => new MemoryStoreInstrumented(sp.GetRequiredService<InMemoryMemoryStore>()));
        services.TryAddSingleton<IMemoryIndex>(sp => sp.GetService<IEmbeddingGenerator<string, Embedding<float>>>() is { } embeddings
            ? new InMemoryMemoryIndex(embeddings)
            : UnavailableMemoryIndex.Instance);
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IAgentContextProviderSource, MemoryContextProviderSource>());
        services.TryAddEnumerable(ServiceDescriptor.Singleton<IToolSource, MemoryToolSource>());
        return builder;
    }

    private static void Normalize(MemoryOptions o)
    {
        if (string.IsNullOrWhiteSpace(o.SharedOwnerId))
        {
            o.SharedOwnerId = null;
        }
    }

    /// <summary>The first violation as text, or null when the options are valid.</summary>
    internal static string? Describe(MemoryOptions o)
    {
        ArgumentNullException.ThrowIfNull(o);
        if (o.Recall is null || o.Dedupe is null)
        {
            return "Recall and Dedupe must not be null.";
        }

        if (o.Recall.TopK < 1)
        {
            return string.Create(CultureInfo.InvariantCulture, $"Recall.TopK must be >= 1 (was {o.Recall.TopK}).");
        }

        if (double.IsNaN(o.Recall.MinScore) || o.Recall.MinScore is < 0 or > 1)
        {
            return string.Create(CultureInfo.InvariantCulture, $"Recall.MinScore must be in [0, 1] (was {o.Recall.MinScore}).");
        }

        if (o.Dedupe.Enabled && (double.IsNaN(o.Dedupe.Threshold) || o.Dedupe.Threshold is <= 0 or > 1))
        {
            return string.Create(CultureInfo.InvariantCulture, $"Dedupe.Threshold must be in (0, 1] when dedupe is enabled (was {o.Dedupe.Threshold}).");
        }

        return null;
    }

    /// <summary>Runs <see cref="Describe"/> when the options are first resolved (and at host start via <c>ValidateOnStart</c>).</summary>
    private sealed class MemoryOptionsValidator : IValidateOptions<MemoryOptions>
    {
        public ValidateOptionsResult Validate(string? name, MemoryOptions options) =>
            Describe(options) is { } violation ? ValidateOptionsResult.Fail("Thalos:Memory: " + violation) : ValidateOptionsResult.Success;
    }
}
