http_port 3128
acl nuget dstdomain .nuget.org {{EXTRA}}
acl SSL_ports port 443
acl CONNECT method CONNECT
http_access deny CONNECT !SSL_ports
http_access allow CONNECT nuget
http_access allow nuget
http_access deny all
cache deny all
access_log daemon:/var/log/squid/access.log squid
