using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Options;
using Thalos.Agents;
using Thalos.Runtime;
using Thalos.Tools;
using ZeroAlloc.Authorization;

namespace Thalos;

/// <summary><see cref="IServiceCollection"/> entry point for Thalos.</summary>
public static class ThalosServiceCollectionExtensions
{
    /// <summary>Registers the Thalos runtime. Configure a provider (e.g. <c>UseAnthropic</c>) and a session store in <paramref name="configure"/>.</summary>
    public static ThalosBuilder AddThalos(this IServiceCollection services, Action<ThalosBuilder>? configure = null)
    {
        ArgumentNullException.ThrowIfNull(services);
        services.AddOptions<ThalosOptions>();
        services.TryAddSingleton(TimeProvider.System);

        var builder = new ThalosBuilder(services);
        configure?.Invoke(builder);

        // generated by ZeroAlloc.Inject from [Singleton] classes (TryAdd — user registrations above win)
        services.AddThalosCoreServices();

        services.TryAddSingleton<IAgentCatalog, OptionsAgentCatalog>();
        services.TryAddSingleton<IAgentNotificationPublisher>(NullAgentNotificationPublisher.Instance);
        services.TryAddSingleton<IToolAuthorizer>(sp => new DefaultToolAuthorizer(
            sp.GetRequiredService<IOptions<ThalosOptions>>().Value.ToolPolicies,
            sp.GetServices<IAuthorizationPolicy>(),
            sp.GetService<Microsoft.Extensions.Logging.ILogger<DefaultToolAuthorizer>>()));
        services.TryAddSingleton<IAgentRuntime>(sp =>
        {
            // fail fast with actionable messages before the dependency graph reports a generic "unable to resolve"
            _ = sp.GetService<IAgentSessionStore>()
                ?? throw new InvalidOperationException("No IAgentSessionStore registered. Call UseInMemorySessionStore() or UseSessionStore<TStore>() inside AddThalos.");
            _ = sp.GetService<IChatClientProvider>()
                ?? throw new InvalidOperationException("No IChatClientProvider registered. Call UseAnthropic(...) (Thalos.NET.Anthropic) or UseChatClientProvider(...) inside AddThalos.");
            return ActivatorUtilities.CreateInstance<ThalosAgentRuntime>(sp);
        });

        return builder;
    }
}
