using ZeroAlloc.StateMachine;

namespace Thalos.Sessions;

/// <summary>
/// Session lifecycle. Source-generated by ZeroAlloc.StateMachine; the second constructor rehydrates a
/// persisted state (the generated <c>_state</c> field is private to this partial class).
/// </summary>
[StateMachine(InitialState = nameof(SessionState.Idle))]
[Transition<SessionState, SessionTrigger>(From = SessionState.Idle, On = SessionTrigger.Start, To = SessionState.Running)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Idle, On = SessionTrigger.Close, To = SessionState.Closed)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.Complete, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.Fail, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.AwaitApproval, To = SessionState.AwaitingApproval)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Approve, To = SessionState.Running)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Deny, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Close, To = SessionState.Closed)]
[Terminal<SessionState>(State = SessionState.Closed)]
public sealed partial class AgentSessionMachine
{
    public AgentSessionMachine() { }

    public AgentSessionMachine(SessionState current) => _state = current;
}
