using ZeroAlloc.StateMachine;

namespace Thalos.Sessions;

#pragma warning disable ZSM0003 // "trigger appears in only one transition — typo?": triggers are single-use by design

/// <summary>
/// Session lifecycle. Source-generated by ZeroAlloc.StateMachine; the second constructor rehydrates a
/// persisted state (the generated <c>_state</c> field is private to this partial class).
/// </summary>
/// <remarks>
/// <c>Running → Close</c> is intentionally absent: a running turn must finish (Complete/Fail) or park in
/// <see cref="SessionState.AwaitingApproval"/> before the session can be closed. <see cref="SessionState.Closed"/>
/// is terminal and rejects every trigger.
/// </remarks>
[StateMachine(InitialState = nameof(SessionState.Idle))]
[Transition<SessionState, SessionTrigger>(From = SessionState.Idle, On = SessionTrigger.Start, To = SessionState.Running)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Idle, On = SessionTrigger.Close, To = SessionState.Closed)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.Complete, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.Fail, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.Running, On = SessionTrigger.AwaitApproval, To = SessionState.AwaitingApproval)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Approve, To = SessionState.Running)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Deny, To = SessionState.Idle)]
[Transition<SessionState, SessionTrigger>(From = SessionState.AwaitingApproval, On = SessionTrigger.Close, To = SessionState.Closed)]
[Terminal<SessionState>(State = SessionState.Closed)]
public sealed partial class AgentSessionMachine
{
    /// <summary>Creates a machine in <see cref="SessionState.Idle"/>.</summary>
    public AgentSessionMachine() { }

    /// <summary>Rehydrates a machine at a persisted state.</summary>
    public AgentSessionMachine(SessionState current) => _state = current;
}

#pragma warning restore ZSM0003
